### ISSUE TITLE
Use GetClientRect instead of GetWindowRect

### ISSUE THREAD

**Issue by Godnoken** [veeenu/hudhook#76] opened 2023-02-05 21:02 UTC
Currently, with `GetWindowRect` we risk having this;
![image](https://user-images.githubusercontent.com/17499594/216845498-392a8729-c8cc-4527-bdd2-6163b5f57ddb.png)

And with `GetClientRect`, we should always get this;
![image](https://user-images.githubusercontent.com/17499594/216845380-f1ec6393-e4cd-4b2e-884f-32af03f1cd2f.png)

The issue at hand is that `GetWindowRect` simply doesn't account for borders, padding etc.

Is there any particular reason that we use `GetWindowRect`?

**Comment by veeenu** [comment] 2023-02-07 08:57
Could you elaborate a bit on the issue? I'm not clear on what's going on in those two cases except that a mouse position is registered.

I honestly think it might've been a long term oversight from when this engine was still written in C++, but I can't rule out the fact that the rectangle influences the rendering sizes somewhere. It would be a good idea to make a review of all the call sites to understand what is going on. But I wouldn't put a super high priority to it unless we can find it breaks some use cases, as we would also have to ensure that `GetClientRect` doesn't introduce regressions.

**Comment by Godnoken** [comment] 2023-02-07 09:21
> Could you elaborate a bit on the issue? I'm not clear on what's going on in those two cases except that a mouse position is registered.

Sorry, I should have explained as it's not 100% clear in the photos hehe.

The issue is that both of the Mouse Position texts disappear due to `GetWindowRect` not taking the TitleBar into account. So 0, 0 will be at the top-left of the TitleBar and not the actual rendering window.
It's really only going to crop up when you play games in windowed mode and even then it doesn't in all games - I'm not sure how(?)

> but I can't rule out the fact that the rectangle influences the rendering sizes somewhere.

Not entirely sure what you mean here, what rectangle?

> It would be a good idea to make a review of all the call sites to understand what is going on. But I wouldn't put a super high priority to it unless we can find it breaks some use cases, as we would also have to ensure that `GetClientRect` doesn't introduce regressions.

I can't really think of anything that would break by changing to `GetClientRect`. I believe all it does is take account for things like the TitleBar, borders, padding etc.

**Comment by veeenu** [comment] 2023-02-07 10:20
> The issue is that both of the Mouse Position texts disappear due to `GetWindowRect` not taking the TitleBar into account. So 0, 0 will be at the top-left of the TitleBar and not the actual rendering window. It's really only going to crop up when you play games in windowed mode and even then it doesn't in all games - I'm not sure how(?)

No clue -- we should assess against some real use cases with videos and look into it.

> > but I can't rule out the fact that the rectangle influences the rendering sizes somewhere.
> 
> Not entirely sure what you mean here, what rectangle?

The rectangle returned by `GetWindowRect` / `GetClientRect`. Depending on which call site you are referring to, using one or the other could influence the size of the drawing surface, thus stretching slightly the aspect ratio of the UI. If you refer to mouse positions, instead, that could influence the pointing mechanism in such a way that the mouse cursor is not on the actual UI items.

> I can't really think of anything that would break by changing to `GetClientRect`. I believe all it does is take account for things like the TitleBar, borders, padding etc.

That's why we should test that thoroughly. I agree it probably won't affect anything, but I can't know for sure.

**Comment by Godnoken** [comment] 2023-02-08 10:37
> The rectangle returned by `GetWindowRect` / `GetClientRect`. Depending on which call site you are referring to, using one or the other could influence the size of the drawing surface, thus stretching slightly the aspect ratio of the UI. If you refer to mouse positions, instead, that could influence the pointing mechanism in such a way that the mouse cursor is not on the actual UI items.

Oh my, haha.. Sometimes I get so used to the abbreviations of words when it comes to programming that I forget what it actually stands for.

I see what you mean, however, so far there's been no mouse misalignment in the games I tried it with & if there would be stretching happening then it would be minimal due to borders, titlebars etc being really small. The one thing I am not sure of however is if there is any code using the position of the `GetWindowRect`, because it is absolute while `GetClientRect` is relative.

Either way, it seems like this issue only exists with the OpenGL renderer as I have only been able to reproduce it there. Which makes me wonder - Does DirectX internally ignore titlebars & borders, or is this something accounted for somewhere else in our render code?

---

Another bug cropped up too on OpenGL fiddling with this. It seems that the Imgui `display_size` isn't being updated on resize. Not sure if this is an upstream issue from https://github.com/Jakobzs/rust-imgui-opengl-renderer or if this can and should be corrected in our code. I don't see any resize/reset hooks and at the moment I don't know how to implement that.

**Comment by veeenu** [comment] 2023-02-13 10:22
> Either way, it seems like this issue only exists with the OpenGL renderer as I have only been able to reproduce it there. Which makes me wonder - Does DirectX internally ignore titlebars & borders, or is this something accounted for somewhere else in our render code?

I don't think I've ever dealt consciously with those on the DX renderers. It could be that it's an issue specifically related to how OpenGL rendering works and thus we could fix it there.
 
> ~Another bug cropped up too on OpenGL fiddling with this. It seems that the Imgui `display_size` isn't being updated on resize. Not sure if this is an upstream issue from https://github.com/Jakobzs/rust-imgui-opengl-renderer or if this can and should be corrected in our code. I don't see any resize/reset hooks and at the moment I don't know how to implement that.~
> 
> Nevermind.. It had nothing to do with `display_size`. I fixed it on my end by setting `Condition::FirstUseEver` to `Condition::Always` on my Imgui window. Interestingly enough that wasn't required on DX9 and DX11. Not sure about DX12 because I don't have the opportunity to try it. I think it is because `DrawCmd::ResetRenderState` is unimplemented in the renderer we use, but that's just a guess.

I'm not sure if that's intended on the `imgui` side, honestly -- `FirstUseEver` makes it sound like it is, but I think at some point we may want to implement `ResetRenderState` much in the same way we overtake `ResizeBuffers` on DX.

**Comment by Godnoken** [comment] 2023-02-13 10:58
> I don't think I've ever dealt consciously with those on the DX renderers. It could be that it's an issue specifically related to how OpenGL rendering works and thus we could fix it there.

Yeah, that's likely. I can take a look at it at some other point - but for now `GetClientRect` works as a hotfix for anyone needing one locally.

> I'm not sure if that's intended on the `imgui` side, honestly -- `FirstUseEver` makes it sound like it is, 

I believe it is indeed intended, however they leave the resizing up to the renderer if used.

> but I think at some point we may want to implement `ResetRenderState` much in the same way we overtake `ResizeBuffers` on DX.

Yup! If no one else gets on it, then I probably will later down the road.

**Comment by veeenu** [comment] 2023-06-27 09:23
Closed by #110.

**Closed by veeenu** 2023-06-27 09:23 UTC
